### ISSUE TITLE
Create game function throws error

### ISSUE THREAD

**Issue by drice89** [drice89/virtual_tabletop#38]
Unhandled Rejection (TypeError): Cannot read property 'data' of undefined
(anonymous function)
src/actions/games_actions.js:53
  50 |       dispatch(receiveGame(resGame.data));
  51 |       return resGame.data.game._id;
  52 |     })
> 53 |     .catch((err) => { dispatch(receiveGameErrors(err.response.data)); })
  54 | );
  55 | 
  56 | export const deleteGame = (gameId) => (dispatch) => (
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by breakfasting** [comment]
fixed in new-grid-bugs by adding an users slice in the createGame controller response payload
